name: Build Android GKI Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: 'Choose Kernel source'
        required: true
        type: choice
        options:
          - gki_kernel@ztc1997
          - lineageos_xiaomi_sm8450
          - fork_melt

      BUILD_NUMBER:
        description: 'ci.android.com build number'
        required: true
        type: string

      ksu_patch:
        description: 'Add KernelSU patch'
        required: false
        type: choice
        options:
          - none
          - release
          - dev

      susfs4ksu_patch:
        description: 'Add susfs4ksu patch'
        required: false
        type: boolean

      ap_patch:
        description: 'Add Apatch release patch'
        required: false
        type: boolean

      ccache_set:
        description: 'Enable Ccache'
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Setup Ccache
        if: ${{ inputs.ccache_set }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G          
        
      - name: Set build date
        id: set-env-date
        run: echo "BUILDDATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Clone build tool
        run: |
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo

          mkdir android_build
          cd android_build
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          ~/.bin/repo init -q -u https://github.com/FlyLoongZ/kernel_build_scripts -b repo_manifest
          ~/.bin/repo sync

          echo "=== Clone android llvm ==="
          mkdir -p prebuilts-master/clang/host/linux-x86
          cd prebuilts-master/clang/host/linux-x86
          git init
          git remote add origin https://mirrors.ustc.edu.cn/aosp/platform/prebuilts/clang/host/linux-x86.git
          if [[ ${{ inputs.kernel_source }} == lineageos_xiaomi_sm8450 ]]; then
            git sparse-checkout set clang-r416183b
            git pull --depth=1 origin master-kernel-build-2021
          else
            git sparse-checkout set clang-r547379
            git pull --depth=1 origin main
            mv clang-r547379 clang-r416183b
          fi

      - name: Clone Kernel source
        run: |
          cd android_build
          if [[ ${{ inputs.kernel_source }} == gki_kernel@ztc1997 ]]; then
            git clone --depth=1 https://github.com/ztc1997/android_gki_kernel_5.10_common.git common
            mv ../0001-ztc1997-build-fix.patch common/
            cd common
            git am 0001-ztc1997-build-fix.patch
          elif [[ ${{ inputs.kernel_source }} == lineageos_xiaomi_sm8450 ]]; then
            git clone --depth=1 https://github.com/cupid-development/android_kernel_xiaomi_sm8450.git common
            mv ../0001-lineageos_xiaomi_sm8450-build-fix.patch common/
            cd common
            git am 0001-lineageos_xiaomi_sm8450-build-fix.patch
          elif [[ ${{ inputs.kernel_source }} == fork_melt ]]; then
            git clone --depth=1 https://github.com/FlyLoongZ/android_kernel_xiaomi_marble.git common
          else
            exit 1
          fi

      - name: Add KernelSU release
        if: contains(inputs.ksu_patch, 'release')
        run: | 
          cd android_build/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          cd KernelSU
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Add KerenlSU dev
        if: contains(inputs.ksu_patch, 'dev')
        run: |
          cd android_build/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          cd KernelSU
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Add susfs4ksu patch
        if: ${{ inputs.susfs4ksu_patch }}
        env:
          ksu_patch_set: ${{ inputs.ksu_patch }}
        run: |
          if [[ ${{ env.ksu_patch_set }} == none ]]; then
            echo "ksu patch no enable"
          else
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10
            cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch android_build/common/KernelSU/
            cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch android_build/common/
            cp susfs4ksu/kernel_patches/fs/* android_build/common/fs/
            cp susfs4ksu/kernel_patches/include/linux/* android_build/common/include/linux/

            cd android_build/common/KernelSU
            patch -p1 < 10_enable_susfs_for_ksu.patch
            cd ..
            patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
          fi

      - name: Set Ccache env
        if: ${{ inputs.ccache_set }}
        run: |
          cd android_build
          mkdir .bin
          cd .bin
          ln -s /usr/bin/ccache clang
          
      - name: Build Kernel
        env: 
          ccache_set: ${{ inputs.ccache_set }}
          choice_kernel: ${{ inputs.kernel_source }}
        run: |
          if [[ ${{ env.ccache_set }} == true ]]; then
            export 'CCACHE_LOCAL_PATH=.bin'
          else
            echo 'No add Ccache'
          fi

          cd android_build/common
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          cd ..

          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 BUILD_NUMBER=${{ inputs.BUILD_NUMBER }} build/build.sh -j4

      - name: Add Apatch
        if: ${{ inputs.ap_patch }}
        env:
          ap_key: ${{ secrets.Apatch_Key }}
        run: |
          cd android_build/out/android12-5.10/dist
          mkdir apatch
          cd apatch
          wget -q https://github.com/bmax121/KernelPatch/releases/latest/download/kptools-linux
          wget -q https://github.com/bmax121/KernelPatch/releases/latest/download/kpimg-android
          mv ../Image ../Image-old
          chmod +x kptools-linux
          ./kptools-linux -p --image ../Image-old --skey "$ap_key" --kpimg kpimg-android --out ../Image
          
      - name: Read Kernel version
        id: set-env-kernel-version
        run: echo "KERNEL_VERSION=$(awk -F'"' '{print $2}' android_build/out/android12-5.10/common/include/generated/utsrelease.h)" >> $GITHUB_OUTPUT

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: "Image-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}"
          path: android_build/out/android12-5.10/dist/Image
      
      - name: Package kerenl
        run: |
          git clone --depth=1 https://github.com/FlyLoongZ/AnyKernel3
          cp android_build/out/android12-5.10/dist/Image AnyKernel3/Image
          cd AnyKernel3
          zip -r9 "Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}.zip" * -x .git README.md
      
      - name: Create release text
        env: 
          ksu_patch: ${{ inputs.ksu_patch }}
          ap_patch: ${{ inputs.ap_patch }}
          susfs4ksu_patch: ${{ inputs.susfs4ksu_patch }}
        run: |
          if [[ ${{ env.ksu_patch }} != none ]]; then
            echo "KernelSU: ✔️" >> release.txt
            echo "KernelSU Version: $KernelSU_version" >> release.txt
            if [[ ${{ env.susfs4ksu_patch }} == true ]]; then
              echo "susfs4ksu: ✔️" >> release.txt
              echo "susfs4ksu Version: $(cat android_build/common/include/linux/susfs.h | grep -E '^#define SUSFS_VERSION' | cut -d' ' -f3 | sed 's/"//g')" >> release.txt
            fi
          fi

          if [[ ${{ env.ap_patch }} == true ]]; then
            echo "Apatch: ✔️" >> release.txt
          fi

          echo "Kernel Version: ${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}" >> release.txt
          echo "Kernel Source: $(cd android_build/common && git remote -v | awk '/https/ {print $2; exit}')" >> release.txt
          echo "Kernel Source Branch: $(cd android_build/common && git branch --show-current)" >> release.txt
          echo "Kernel Source Commit: $(cd android_build/common && git rev-parse --short HEAD)" >> release.txt
      
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.set-env-date.outputs.BUILDDATE }}.${{ github.run_number }}
          files: "AnyKernel3/Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}.zip"
          body_path: release.txt
