name: Build Android GKI Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_source_url:
        description: 'Choose Kernel source url'
        required: true
        type: choice
        options:
          - ztc1997-5.10
          - melt-release
          - melt-latest

      BUILD_NUMBER:
        description: 'ci.android.com build number'
        required: true
        type: string

      ksu_patch:
        description: 'Add KernelSU patch'
        required: false
        type: choice
        options:
          - none
          - release
          - dev

      ap_patch:
        description: 'Add Apatch release patch'
        required: false
        type: boolean

      ccache_set:
        description: 'Enable CCache'
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CCache
        if: ${{ inputs.ccache_set }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G          
        
      - name: Set Build Date
        id: set-env-date
        run: echo "BUILDDATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Clone Build Tool
        run: |          
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo

          mkdir android_build
          cd android_build
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          ~/.bin/repo init -q -u https://github.com/FlyLoongZ/kernel_build_scripts -b repo_manifest
          ~/.bin/repo sync

          mkdir -p prebuilts-master/clang/host/linux-x86/clang-r416183b
          git clone --filter=blob:none --sparse https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 tmp-clone
          cd tmp-clone
          git sparse-checkout add clang-r547379
          mv clang-r547379 ../prebuilts-master/clang/host/linux-x86/clang-r416183b

      - name: Clone Kernel Source
        env:
          kernel_source_url: ${{ inputs.kernel_source_url }}
        run: |
          cd android_build
          if [[ ${{ env.kernel_source_url}} == ztc1997-5.10 ]]; then
            git clone --filter=tree:0 https://github.com/ztc1997/android_gki_kernel_5.10_common common
            cd common
            git tag -a v5.10.226 -m "android12-5.10" fbe645b
            sed -i '1d' arch/arm64/configs/gki_defconfig
            sed -i '116,121d' scripts/setlocalversion
          elif [[ ${{ env.kernel_source_url}} == melt-release ]]; then
            git clone --filter=tree:0 https://github.com/Pzqqt/android_kernel_xiaomi_marble common -b $(git ls-remote --sort=-version:refname --tags https://github.com/Pzqqt/android_kernel_xiaomi_marble Melt-marble-v\* | head -n 1 | awk -F'/' '{print $NF}')
            cd common
            git tag -d $(git describe --tags)
            sed -i '1,5d' arch/arm64/configs/marble_defconfig
            sed -i '116,121d' scripts/setlocalversion
            sed -i '/source "drivers\/staging\/kernelsu\/Kconfig"/d' drivers/staging/Kconfig
            sed -i '/obj-\$(CONFIG_KSU)[[:space:]]*+= kernelsu\//d' drivers/staging/Makefile
            rm -r drivers/staging/kernelsu
          elif [[ ${{ env.kernel_source_url}} == melt-latest ]]; then
            git clone --filter=tree:0 https://github.com/Pzqqt/android_kernel_xiaomi_marble common
            cd common
            sed -i '1,5d' arch/arm64/configs/marble_defconfig
            sed -i '116,121d' scripts/setlocalversion
            sed -i '/source "drivers\/staging\/kernelsu\/Kconfig"/d' drivers/staging/Kconfig
            sed -i '/obj-\$(CONFIG_KSU)[[:space:]]*+= kernelsu\//d' drivers/staging/Makefile
            rm -r drivers/staging/kernelsu
          else
            exit 1
          fi

      - name: Add KernelSU Release
        if: contains(inputs.ksu_patch, 'release')
        run: | 
          cd android_build/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          cd KernelSU
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Add KerenlSU Dev
        if: contains(inputs.ksu_patch, 'dev')
        run: |
          cd android_build/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          cd KernelSU
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Set CCache Env
        if: ${{ inputs.ccache_set }}
        run: |
          cd android_build
          mkdir .bin
          cd .bin
          ln -s /usr/bin/ccache clang
          
      - name: Build Kernel
        env: 
          ccache_set: ${{ inputs.ccache_set }}
          choice_kernel: ${{ inputs.kernel_source_url }}
        run: |
          if [[ ${{ env.ccache_set }} == true ]]; then
            export 'CCACHE_LOCAL_PATH=.bin'
          else
            echo 'No add CCache'
          fi

          cd android_build/common
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          echo -e ". \${ROOT_DIR}/\${KERNEL_DIR}/build.config.common\n. \${ROOT_DIR}/\${KERNEL_DIR}/build.config.aarch64\nDEFCONFIG=marble_defconfig\n" >> build.config.xiaomi
          cd ..

          if [[ ${{ env.choice_kernel }} == ztc1997-5.10 ]]; then
            LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 BUILD_NUMBER=${{ inputs.BUILD_NUMBER }} build/build.sh -j4
          else
            LTO=thin BUILD_CONFIG=common/build.config.xiaomi BUILD_NUMBER=${{ inputs.BUILD_NUMBER }} build/build.sh -j4
          fi

      - name: Add Apatch
        if: ${{ inputs.ap_patch }}
        env:
          ap_key: ${{ secrets.Apatch_Key }}
        run: |
          cd android_build/out/android12-5.10/dist
          mkdir apatch
          cd apatch
          wget -q https://github.com/bmax121/KernelPatch/releases/latest/download/kptools-linux
          wget -q https://github.com/bmax121/KernelPatch/releases/latest/download/kpimg-android
          mv ../Image ../Image-old
          chmod +x kptools-linux
          ./kptools-linux -p --image ../Image-old --skey "$ap_key" --kpimg kpimg-android --out ../Image
          
      - name: Read Kernel Version
        id: set-env-kernel-version
        run: echo "KERNEL_VERSION=$(basename $(find ./android_build/out/android12-5.10/staging/lib/modules/ -name "*android12*"))" >> $GITHUB_OUTPUT

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: "Image-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}-ab${{ inputs.BUILD_NUMBER }}"
          path: android_build/out/android12-5.10/dist/Image
      
      - name: Package Kerenl
        run: |
          git clone --depth=1 https://github.com/FlyLoongZ/AnyKernel3
          cp android_build/out/android12-5.10/dist/Image AnyKernel3/Image
          cd AnyKernel3
          zip -r9 "Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}-ab${{ inputs.BUILD_NUMBER }}.zip" * -x .git README.md
      
      - name: Create Release Text
        env: 
          ksu_patch: ${{ inputs.ksu_patch }}
          ap_patch: ${{ inputs.ap_patch }}
        run: |
          if [[ ${{ env.ksu_patch }} != none ]]; then
            echo "KernelSU: ✔️" >> release.txt
            echo "KernelSU Version: $KernelSU_version" >> release.txt
          else
            echo "KernelSU: ❌" >> release.txt
          fi

          if [[ ${{ env.ap_patch }} == true ]]; then
            echo "Apatch: ✔️" >> release.txt
          else
            echo "Apatch: ❌" >> release.txt
          fi

          echo "Kernel Version: ${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}-ab${{ inputs.BUILD_NUMBER }}" >> release.txt
          echo "Kernel Source: $(cd android_build/common && git remote -v | awk '/https/ {print $2; exit}')" >> release.txt
          echo "Kernel Source Branch: $(cd android_build/common && git branch --contains HEAD -r | awk '/->/ {sub(/.*-> /, "", $0); print substr($0, index($0, "/") + 1)}')" >> release.txt
          echo "Kernel Source Commit: $(cd android_build/common && git rev-parse --short HEAD)" >> release.txt
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.set-env-date.outputs.BUILDDATE }}.${{ github.run_number }}
          files: "AnyKernel3/Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}-ab${{ inputs.BUILD_NUMBER }}.zip"
          body_path: release.txt
