name: Build Android GKI Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: 'Choose Kernel source'
        required: true
        type: choice
        options:
          - aosp-5.10
          - msm-5.10
          - lineageos_xiaomi_sm8450

      BUILD_NUMBER:
        description: 'ci.android.com build number'
        required: true
        type: string

      ksu_patch:
        description: 'Add KernelSU patch'
        required: false
        type: choice
        options:
          - none
          - official_release
          - official_dev
          - sukisu_ultra

      susfs4ksu_patch:
        description: 'Add susfs4ksu patch'
        required: false
        type: boolean

      ccache_set:
        description: 'Enable Ccache'
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Setup Ccache
        if: ${{ inputs.ccache_set }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G          
        
      - name: Set build date
        id: set-env-date
        run: echo "BUILDDATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Clone build tool
        run: |
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
          mkdir android_build_kernel
          cd android_build_kernel
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          ~/.bin/repo init -q -u https://github.com/FlyLoongZ/kernel_build_scripts -b repo_manifest
          ~/.bin/repo sync

          echo "=== Clone android llvm ==="
          mkdir -p prebuilts-master/clang/host/linux-x86
          cd prebuilts-master/clang/host/linux-x86
          echo "- Choose clang-r416183b1"
          git clone https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b1 clang-r416183b

      - name: Clone Kernel source
        run: |
          cd android_build_kernel
          if [[ ${{ inputs.kernel_source }} == aosp-5.10 ]]; then
            echo "=== Choose aosp-5.10 source ==="
            git clone --depth=1 https://android.googlesource.com/kernel/common -b android12-5.10-2025-02 common
            mv ../0001-Modify-kernel-version-logic.patch common/
            cd common
            patch -p1 < 0001-Modify-kernel-version-logic.patch
          elif [[ ${{ inputs.kernel_source }} == msm-5.10 ]]; then
            echo "=== Choose msm-5.10 ==="
            git clone --depth=1 https://pages.codelinaro.org/clo/la/kernel/msm-5.10 -b kernel.lnx.5.10.r1-rel common
            mv ../0001-Modify-kernel-version-logic.patch common/
            mv ../0001-msm-5.10-build-fix.patch common/
            cd common
            patch -p1 < 0001-Modify-kernel-version-logic.patch
            patch -p1 < 0001-msm-5.10-build-fix.patch
          elif [[ ${{ inputs.kernel_source }} == lineageos_xiaomi_sm8450 ]]; then
            echo "=== Choose lineageos_xiaomi_sm8450 source ==="
            git clone --depth=1 https://github.com/cupid-development/android_kernel_xiaomi_sm8450.git common
            mv ../0001-lineageos_xiaomi_sm8450-build-fix.patch common/
            cd common
            cd common
            patch -p1 < 0001-lineageos_xiaomi_sm8450-build-fix.patch
          fi

      - name: Add the official KernelSU release
        if: contains(inputs.ksu_patch, 'official_release')
        run: | 
          cd android_build_kernel/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          cd KernelSU
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Add the official KerenlSU dev
        if: contains(inputs.ksu_patch, 'official_dev')
        run: |
          cd android_build_kernel/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          echo "KernelSU_version=$(expr 10200 + $(git rev-list --count HEAD))"  >> "$GITHUB_ENV"

      - name: Add the SukiSU-Ultra
        if: contains(inputs.ksu_patch, 'sukisu_ultra')
        run: |
          cd android_build_kernel/common
          if [[ ${{ inputs.susfs4ksu_patch }} == true ]]; then
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          else
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
          fi
          echo "KernelSU_version=$(expr 10700 + $(git rev-list --count main))"  >> "$GITHUB_ENV"

      - name: Add the susfs4ksu patch
        if: ${{ inputs.susfs4ksu_patch }}
        env:
          ksu_patch_set: ${{ inputs.ksu_patch }}
        run: |
          if [[ ${{ env.ksu_patch_set }} == none ]]; then
            echo "!!! KernelSU patch no enable !!!"
          elif [[ ${{ env.ksu_patch_set }} == sukisu_ultra ]]; then
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10
            git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git
            echo "=== Copy susfs4ksu file ==="
            cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch android_build_kernel/common/
            cp susfs4ksu/kernel_patches/fs/* android_build_kernel/common/fs/
            cp susfs4ksu/kernel_patches/include/linux/* android_build_kernel/common/include/linux/

            echo "=== Copy SukiSU_patch file ==="
            cp SukiSU_patch/69_hide_stuff.patch android_build_kernel/common/
            cp SukiSU_patch/hooks/syscall_hooks.patch android_build_kernel/common/
            cp gki_defconfig_sukisu.patch android_build_kernel/common/

            echo "=== Start susfs4ksu patch ==="
            cd android_build_kernel/common
            echo "- Patch 50_add_susfs_in_gki-android12-5.10.patch"
            patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch

            echo "=== Start SukiSU_patch patch ==="
            echo "- Patch 69_hide_stuff.patch"
            patch -p1 < 69_hide_stuff.patch
            echo "- Patch syscall_hooks.patch"
            patch -p1 < syscall_hooks.patch
            echo "- Patch gki_defconfig_sukisu.patch"
            patch -p1 < gki_defconfig_sukisu.patch
          else
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10
            echo "=== Copy susfs4ksu file ==="
            cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch android_build_kernel/common/KernelSU/
            cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch android_build_kernel/common/
            cp susfs4ksu/kernel_patches/fs/* android_build_kernel/common/fs/
            cp susfs4ksu/kernel_patches/include/linux/* android_build_kernel/common/include/linux/

            cd android_build_kernel/common/KernelSU
            echo "=== Start susfs4ksu patch ==="
            echo "- Patch 10_enable_susfs_for_ksu.patch"
            patch -p1 < 10_enable_susfs_for_ksu.patch
            cd ..
            echo "- Patch 50_add_susfs_in_gki-android12-5.10.patch"
            patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
          fi

      - name: Set Ccache env
        if: ${{ inputs.ccache_set }}
        run: |
          cd android_build_kernel
          mkdir .bin
          cd .bin
          ln -s /usr/bin/ccache clang
          
      - name: Build Kernel
        env: 
          ccache_set: ${{ inputs.ccache_set }}
          choice_kernel: ${{ inputs.kernel_source }}
        run: |
          if [[ ${{ env.ccache_set }} == true ]]; then
            export "CCACHE_LOCAL_PATH=.bin"
          else
            echo "=== No add Ccache ==="
          fi

          cd android_build_kernel/common
          git config --global user.email build-user@build-host
          git config --global user.name build-user
          cd ..

          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 BUILD_NUMBER=${{ inputs.BUILD_NUMBER }} build/build.sh -j4

      - name: Read Kernel version
        id: set-env-kernel-version
        run: echo "KERNEL_VERSION=$(awk -F'"' '{print $2}' android_build_kernel/out/android12-5.10/common/include/generated/utsrelease.h)" >> $GITHUB_OUTPUT

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: "Image-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}"
          path: android_build_kernel/out/android12-5.10/common/arch/arm64/boot/Image
      
      - name: Package the kerenl
        run: |
          git clone --depth=1 https://github.com/FlyLoongZ/AnyKernel3
          cp android_build_kernel/out/android12-5.10/common/arch/arm64/boot/Image AnyKernel3/Image
          cd AnyKernel3
          zip -r9 "Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}.zip" * -x .git README.md

      - name: Create release text
        run: |
          if [[ ${{ inputs.ksu_patch }} != none ]]; then
            echo "KernelSU: ✔️ (${{ inputs.ksu_patch }})" >> release.txt
            echo "- Version: $(cd android_build_kernel/common/KernelSU && expr 10200 + $(git rev-list --count HEAD))" >> release.txt
            echo "- Commit: $(cd android_build_kernel/common/KernelSU && git rev-parse --short HEAD)" >> release.txt
            if [[ ${{ inputs.susfs4ksu_patch }} == true ]]; then
              echo "susfs4ksu: ✔️" >> release.txt
              echo "- Version: $(cat android_build_kernel/common/include/linux/susfs.h | grep -E '^#define SUSFS_VERSION' | cut -d' ' -f3 | sed 's/"//g')" >> release.txt
              echo "- Branch: $(cd susfs4ksu && git branch --show-current)" >> release.txt
              echo "- Commit: $(cd susfs4ksu && git rev-parse --short HEAD)" >> release.txt
            fi
          fi

          echo "Kernel Version: ${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}" >> release.txt
          echo "- Source: [${{ inputs.kernel_source }}]($(cd android_build_kernel/common && git remote -v | awk '/https/ {print $2; exit}'))" >> release.txt
          echo "- Branch: $(cd android_build_kernel/common && git branch --show-current)" >> release.txt
          echo "- Commit: $(cd android_build_kernel/common && git rev-parse --short HEAD)" >> release.txt
      
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.set-env-date.outputs.BUILDDATE }}.${{ github.run_number }}
          files: "AnyKernel3/Anykernel3-${{ steps.set-env-kernel-version.outputs.KERNEL_VERSION }}.zip"
          body_path: release.txt
